### ISSUE TITLE
Create Kibana rules for community suricata sigs

### ISSUE THREAD

**Issue by dcode** [dcode/tasklist#1]
- [ ] 10004953  ATTACK [PTsecurity] Apache Tomcat RCE on Windows (CVE-2019-0232)
- [ ] 10004555 | ATTACK [PTsecurity] Arbitrary PHP RCE in Drupal 8 < 8.5.11,8.6.10 (CVE-2019-6340)
- [ ] 10004699 | ATTACK [PTsecurity] Confluence <6.14.2,6.13.3,6.12.3 Unauthorized RCE (CVE-2019-3396)
- [ ] 10004529 | ATTACK [PTsecurity] Jenkins sandbox bypassing RCE (CVE-2019-1003000/1/2)
- [ ] 10004779 | ATTACK [PTsecurity] Oracle Weblogic _async deserialization RCE Attempt (CVE-2019-2725)
- [ ] 10004927 | ATTACK [PTsecurity] Oracle Weblogic _async deserialization RCE Attempt (CVE-2019-2725)
- [ ] 10004781 | ATTACK [PTsecurity] Oracle Weblogic file upload RCE (CVE-2019-2618)
- [ ] 10004698 | ATTACK [PTsecurity] Possible Apache Axis RCE via SSRF (CVE-2019-0227)
- [x] 10004867 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708
- [x] 10004864 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (MCS Channel Join Requests)
- [x] 10005399 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (MCS Channel Join Requests)
- [x] 10004861 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #1)
- [x] 10005396 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #1)
- [x] 10005400 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #12)
- [x] 10004865 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #12)
- [x] 10004862 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #2)
- [x] 10005397 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #2)
- [x] 10004863 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #3)
- [x] 10005398 | ATTACK [PTsecurity] Possible Bluekeep RDP exploit CVE-2019-0708 (pkt #3)
- [x] 2027369 | ET EXPLOIT [NCC GROUP] Possible Bluekeep Inbound RDP Exploitation Attempt (CVE-2019-0708)
- [x] 2027451 | ET EXPLOIT Attempted Remote Command Injection Inbound (CVE-2019-3929)
- [x] 2027450 | ET EXPLOIT Attempted Remote Command Injection Outbound (CVE-2019-3929)
- [ ] 2029159 | ET EXPLOIT Enigma Network Management Systems v65.0.0 CVE-2019-16072 (Inbound)
- [ ] 2029158 | ET EXPLOIT Enigma Network Management Systems v65.0.0 CVE-2019-16072 (Outbound)
- [ ] 2027721 | ET EXPLOIT IE Scripting Engine Memory Corruption Vulnerability (CVE-2019-0752)
- [ ] 2029207 | ET EXPLOIT Linear eMerge E3 Unauthenticated Command Injection Inbound (CVE-2019-7256)
- [ ] 2026860 | ET EXPLOIT Possible Cisco RV320 RCE Attempt (CVE-2019-1652)
- [ ] 2029206 | ET EXPLOIT Possible Citrix Application Delivery Controller Arbitrary Code Execution Attempt (CVE-2019-19781)
- [ ] 2029255 | ET EXPLOIT Possible Citrix Application Delivery Controller Arbitrary Code Execution Attempt (CVE-2019-19781) M2
- [ ] 2027442 | ET EXPLOIT Possible Exim 4.87-4.91 RCE Attempt Inbound (CVE-2019-10149
- [ ] 2028636 | ET EXPLOIT Possible EXIM DoS (CVE-2019-16928)
- [ ] 2027959 | ET EXPLOIT Possible EXIM RCE Inbound (CVE-2019-15846)
- [ ] 2027960 | ET EXPLOIT Possible EXIM RCE Inbound (CVE-2019-15846) M2
- [ ] 2028933 | ET EXPLOIT Possible rConfig 3.9.2 Remote Code Execution PoC (CVE-2019-16662)
- [ ] 2027696 | ET EXPLOIT Possible Zoom Client Auto-Join (CVE-2019-13450
- [ ] 2027904 | ET EXPLOIT Pulse Secure SSL VPN - Arbitrary File Read (CVE-2019-11510)
- [ ] 2028621 | ET EXPLOIT vBulletin 5.x Unauthenticated Remote Code Execution (CVE-2019-16759) M1
- [ ] 2028825 | ET EXPLOIT vBulletin 5.x Unauthenticated Remote Code Execution (CVE-2019-16759) M2
- [ ] 2028826 | ET EXPLOIT vBulletin 5.x Unauthenticated Remote Code Execution (CVE-2019-16759) M3
- [ ] 2028928 | ET EXPLOIT VMware VeloCloud Authorization Bypass (CVE-2019-5533)
- [ ] 2029153 | ET EXPLOIT Yachtcontrol Webservers RCE CVE-2019-17270 (Inbound)
- [ ] 2029152 | ET EXPLOIT Yachtcontrol Webservers RCE CVE-2019-17270 (Outbound)
- [ ] 2027315 | ET WEB_CLIENT Attempted RCE in Wordpress Social Warfare Plugin Inbound (CVE-2019-9978
- [ ] 2027333 | ET WEB_CLIENT Possible Confluence SSTI Exploitation Attempt - Leads to RCE/LFI (CVE-2019-3396)
- [ ] 2028895 | ET WEB_SERVER Possible PHP Remote Code Execution CVE-2019-11043 PoC (Inbound)
- [ ] 2027896 | ET WEB_SERVER Webmin RCE CVE-2019-15107
- [ ] 2027706 | ET WEB_SPECIFIC_APPS Appointment Hour Booking - WordPress Plugin - Stored XSS (CVE-2019-13505)
- [ ] 2027712 | ET WEB_SPECIFIC_APPS Atlassian Crowd Plugin Upload Attempt (CVE-2019-11580)
- [ ] 2027711 | ET WEB_SPECIFIC_APPS Atlassian JIRA Template Injection RCE (CVE-2019-11581
- [ ] 2027368 | ET WEB_SPECIFIC_APPS Cisco Prime Infrastruture RCE - CVE-2019-1821
- [ ] 2027349 | ET WEB_SPECIFIC_APPS Jenkins Chained Exploits CVE-2018-1000861 and CVE-2019-1003000 M1
- [ ] 2027350 | ET WEB_SPECIFIC_APPS Jenkins Chained Exploits CVE-2018-1000861 and CVE-2019-1003000 M2
- [ ] 2027346 | ET WEB_SPECIFIC_APPS Jenkins RCE CVE-2019-1003000
- [ ] 2027345 | ET WEB_SPECIFIC_APPS Possible SharePoint RCE Attempt (CVE-2019-0604)
- [ ] 2027096 | ET WEB_SPECIFIC_APPS Rails Arbitrary File Disclosure Attempt
